### ISSUE TITLE
Arrange meeting between principle project stakeholders

### ISSUE THREAD

**Issue by brylie** [apinf/openapi-space#20]
In order to make sure this project meets the needs/goals of the main stakeholders, it is important that we meet briefly, and perhaps periodically. Lets set up an initial meeting, where we can agree on our work and goals.

cc: @MikeRalphson @ccsr @tulir @xylix @bajiat 

Please add a comment below, or thumbs up to this issue, to indicate interest.

**Comment by brylie** [comment]
If you are interested in meeting via video and/or audio, please add a comment with your timezone. I will set up Doodle to find the best meeting time, based on our timezones and availability.

**Comment by mauriciovieira** [comment]
[UTC-3](https://www.timeanddate.com/time/zones/brt)

**Comment by MikeRalphson** [comment]
[UTC+1](https://www.timeanddate.com/time/zones/bst)

**Comment by xylix** [comment]
UTC+3

**Comment by Nazarah** [comment]
UTC+3

**Comment by ccsr** [comment]
@brylie sorry for not being specific here. I requested for a meeting between Mike, myself, you and @bajiat to discuss about how we collaborate in OpenAPI Spec area regarding to APInf. It is not going to be technical discussion and I think we will be wasting time of developers here. My main target is to understand Mike's business goals with this project and aligh APInf's business goal or find a common ground of collaboration. 
For future of course I encourage the whole team to meet at least once in a fortnight and discuss technical issues, but I dont have to be there in those meetings. 

For this meeting lets make it simple so that we find time from the limited group.

**Comment by brylie** [comment]
> For this meeting lets make it simple so that we find time from the limited group.

OK, I understand.

We can leave this issue open, and schedule a broader stakeholder meeting in the coming weeks.
